name: Deployment

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy PhilNITS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build the site
        run: npm run build

      - name: Upload file to SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}
          port: ${{secrets.SSH_PORT}}
          source: ".next/*, package.json, public/*, next.config.ts"
          target: "~/philnits.dcism.org/"
          overwrite: true

      - name: Build
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd ~/philnits.dcism.org
            npm install --legacy-peer-deps
            npx pm2 restart philnits || npx pm2 start npm --name 'philnits' -- start 